# This template is the base template required to exist for all other templates to work
# It has some common jobs shared between all the templates provided.
# Required CI templates: none
# When using the template for setting up a yamato job, please include the following disclaimer:
#_________________________________________________
# If you make changes to this file, please consider making a PR to the templating repo!
# Please find the source file here: https://github.cds.internal.unity3d.com/unity/yamato-ci-templates/blob/master/.yamato/base.yml
# VERSION 1
#_________________________________________________

# Configuration #######################################

######################################################
# Avoid tampering with stuff below here if you can

{% metadata_file .yamato/template-config.metafile %}

template_environment_variables:
  # Do not touch
  JOB_TEMPLATE_VERSION: 1
---

{% for platform in platforms %}
{% for editor in editors %}
editor:priming:{{ editor.version }}:{{ platform.os }}:
  name: Editor priming for {{ editor.version }} on {{ platform.os }}
  agent:
    type: Unity::VM
    image: 'cds-ops/ubuntu-16.04-base:stable'
    flavor: b1.small
  variables:
    PATH: /home/bokken/bin:/home/bokken/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/sbin:/home/bokken/.npm-global/bin
    DISPLAY: ":0"
    {% for v in template_environment_variables %}
    {{ v[0] }}: {{ v[1]}}
    {% endfor %}
  commands:
    - pip install unity-downloader-cli --user --upgrade --index-url https://artifactory.prd.it.unity3d.com/artifactory/api/pypi/pypi/simple
    - >
      unity-downloader-cli
      -u {{ editor.version }}
      -o {{ platform.os }}
      --wait
      --skip-download
{% for component in platform.components -%}
      -c {{ component }}
{% endfor -%}
      > unity_revision.txt
  artifacts:
    unity_revision.zip:
      paths:
        - "unity_revision.txt"
{% endfor -%}
{% for test in testables %}
editor:priming:{{ test.name }}:{{ platform.os }}:
  name: Editor priming for {{ test.name }} on {{ platform.os }}
  agent:
    type: Unity::VM
    image: 'cds-ops/ubuntu-16.04-base:stable'
    flavor: b1.small
  variables:
    PATH: /home/bokken/bin:/home/bokken/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/sbin:/home/bokken/.npm-global/bin
    DISPLAY: ":0"
    {% for v in template_environment_variables %}
    {{ v[0] }}: {{ v[1]}}
    {% endfor %}
  commands:
    - pip install unity-downloader-cli --user --upgrade --index-url https://artifactory.prd.it.unity3d.com/artifactory/api/pypi/pypi/simple
    - >
      unity-downloader-cli
      -u {{ test.path }}
      -o {{ platform.os }}
      --wait
      --skip-download
{% for component in platform.components -%}
      -c {{ component }}
{% endfor -%}
      > unity_revision.txt
{% endfor -%}
  artifacts:
    unity_revision.zip:
      paths:
        - "unity_revision.txt"
{% endfor %}